# Generated by Django 3.2.5 on 2022-08-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_machine_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldData',
            fields=[
                ('status', models.IntegerField(default=0)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mod_no', models.CharField(max_length=100)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machine')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.process')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
        ),
    ]
