# Generated by Django 3.2.5 on 2022-08-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220819_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molddata',
            name='status',
        ),
    ]
