# Generated by Django 3.2.5 on 2022-08-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_molddata_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molddata',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
