# Generated by Django 3.2.5 on 2022-08-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220822_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molddata',
            name='start_time',
            field=models.DateTimeField(default='2022-08-24 15:31:03'),
        ),
        migrations.AlterField(
            model_name='molddata',
            name='times',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
