# Generated by Django 3.2.5 on 2022-08-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220824_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(default='2022-08-24 16:39:12')),
            ],
        ),
        migrations.DeleteModel(
            name='Statics',
        ),
        migrations.AlterField(
            model_name='molddata',
            name='start_time',
            field=models.DateTimeField(default='2022-08-24 16:39:12'),
        ),
    ]
