# Generated by Django 3.2.5 on 2022-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_molddata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='molddata',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
